Repository NCAS-CMS/cf-python, pull requests merged in 2022-02, with the labels that each got.

#308 LAMA to Dask: `func` -> built-in conversion for non-trig. methods
  cf/data/data.py
  cf/test/test_Data.py
Labels: performance, dask

#309 LAMA to Dask: func -> built-in conversion for trig. methods
  cf/data/data.py
Labels: performance, dask

#312 dask: `Dask.digitize`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#313 dask: `Data.percentile`, `Data.median`
  cf/__init__.py
  cf/data/dask_utils.py
  cf/data/data.py
  cf/field.py
  cf/test/test_Data.py
  requirements.txt
Labels: dask

#315 dask: `Data.empty`, `Data.full`, `Data.ones`, `Data.zeros`
  cf/data/data.py
  cf/docstring/docstring.py
  cf/test/test_Data.py
Labels: dask

#319 dask: `Data.__bool__`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#323 Manage warnings in `test_Data`
  cf/test/test_Data.py
Labels: code tidy, testing, dask

#301 `Data.mask`: migrate to Dask
  cf/data/data.py
  cf/test/test_Data.py
Labels: question, dask

#322 dask: `Data_asreftime`; `Data._asdatetime`; `Data.year` & friends
  cf/data/dask_utils.py
  cf/data/data.py
  cf/data/utils.py
  cf/test/test_Data.py
Labels: dask

#321 dask: `Data.__iter__`, `Data.__len__`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask
