Repository NCAS-CMS/cf-python, pull requests merged in 2022-03, with the labels that each got.

#330 dask: fix `Data.equals` for arbitrary chunk distributions
  cf/data/dask_utils.py
  cf/test/test_Data.py
Labels: dask

#320 dask: `Data.__contains__`
  cf/data/dask_utils.py
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#334 dask: `Data.asdata`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#337 dask: `Data.__float__` and `Data.__int__`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#335 dask: `Data.change_calendar`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#333 dask: `Data.flatten`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#340 dask: `Data.filled`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#350 dask: `Data.diff`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#343 dask: `Dask cumsum`
  cf/data/data.py
  cf/functions.py
  cf/test/test_Data.py
Labels: dask

#331 dask: `Data.halo`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#352 dask: `Data.roll`
  cf/test/test_Data.py
Labels: dask

#355 dask: `Data.chunks` and `Data.rechunk`
  cf/data/data.py
  cf/docstring/docstring.py
  cf/test/test_Data.py
Labels: dask

#344 dask: `Dask.cyclic`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#338 dask: `Data.HDF_chunks`
  cf/data/data.py
  cf/functions.py
Labels: dask

#353 dask: `Data.array` and friends
  cf/__init__.py
  cf/cfdatetime.py
  cf/data/creation.py
  cf/data/data.py
  cf/data/utils.py
  cf/test/test_Data.py
  cf/test/test_Data_utils.py
  cf/timeduration.py
  docs/source/installation.rst
  requirements.txt
Labels: dask

#357 dask: `Data` units and calendar methods inherited from cfdm
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#362 `data` batch docstring re-formatting: 'Examples:' -> 'Examples'
  cf/data/abstract/compressedsubarray.py
  cf/data/abstract/filearray.py
  cf/data/cachedarray.py
  cf/data/collapse_functions.py
  cf/data/creation.py
  cf/data/data.py
  cf/data/filledarray.py
  cf/data/functions.py
  cf/data/mixin/deprecations.py
  cf/data/netcdfarray.py
  cf/data/partition.py
  cf/data/partitionmatrix.py
  cf/data/umarray.py
  cf/data/utils.py
Labels: documentation, code tidy, dask

#364 Revert "docstring re-formatting: 'Examples:' -> 'Examples'"
  cf/data/abstract/compressedsubarray.py
  cf/data/abstract/filearray.py
  cf/data/cachedarray.py
  cf/data/collapse_functions.py
  cf/data/creation.py
  cf/data/data.py
  cf/data/filledarray.py
  cf/data/functions.py
  cf/data/mixin/deprecations.py
  cf/data/netcdfarray.py
  cf/data/partition.py
  cf/data/partitionmatrix.py
  cf/data/umarray.py
  cf/data/utils.py
Labels: documentation, code tidy

#363 Batch docstring formatting update: 'Examples:' -> 'Examples'
  cf/abstract/constructlist.py
  cf/aggregate.py
  cf/bounds.py
  cf/cellmeasure.py
  cf/cellmethod.py
  cf/cfdatetime.py
  cf/cfimplementation.py
  cf/constructlist.py
  cf/constructs.py
  cf/coordinatereference.py
  cf/dimensioncoordinate.py
  cf/domain.py
  cf/domainaxis.py
  cf/field.py
  cf/fieldlist.py
  cf/flags.py
  cf/functions.py
  cf/maths.py
  cf/mixin/coordinate.py
  cf/mixin/fielddomain.py
  cf/mixin/fielddomainlist.py
  cf/mixin/properties.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/query.py
  cf/read_write/netcdf/netcdfread.py
  cf/read_write/netcdf/netcdfwrite.py
  cf/read_write/read.py
  cf/read_write/um/filearray.py
  cf/read_write/um/functions.py
  cf/read_write/um/umread.py
  cf/read_write/write.py
  cf/regrid/regridoperator.py
  cf/subspacefield.py
  cf/timeduration.py
Labels: documentation, code tidy
