Repository NCAS-CMS/cf-python, pull requests merged in 2022-11, with the labels that each got.

#432 LAMA to Dask migration: `Data.stats`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#466 dask: `Field.percentile`
  cf/data/data.py
  cf/field.py
  cf/test/test_Data.py
  cf/test/test_Field.py
Labels: dask

#486 dask: Set `Data._axes` in reshape and binary arithmetic
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#485 dask: Changes to allow test_docstring.py to pass
  cf/data/data.py
  cf/data/mixin/arraymixin.py
Labels: dask

#465 Specify all @_deprecated_kwarg_check() versions
  README.release.md
  cf/abstract/constructlist.py
  cf/bounds.py
  cf/cellmeasure.py
  cf/cellmethod.py
  cf/constructlist.py
  cf/coordinatereference.py
  cf/data/data.py
  cf/decorators.py
  cf/dimensioncoordinate.py
  cf/field.py
  cf/flags.py
  cf/functions.py
  cf/mixin/coordinate.py
  cf/mixin/fielddomain.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/query.py
  cf/timeduration.py
Labels: dask

#476 Changes to facilitate CFA-0.6
  cf/__init__.py
  cf/cfimplementation.py
  cf/data/__init__.py
  cf/data/abstract/compressedsubarray.py
  cf/data/array/__init__.py
  cf/data/array/abstract/__init__.py
  cf/data/array/abstract/array.py
  cf/data/array/abstract/filearray.py
  cf/data/array/cachedarray.py
  cf/data/array/cfanetcdfarray.py
  cf/data/array/fullarray.py
  cf/data/array/gatheredarray.py
  cf/data/array/mixin/__init__.py
  cf/data/array/mixin/arraymixin.py
  cf/data/array/mixin/filearraymixin.py
  cf/data/array/mixin/raggedarraymixin.py
  cf/data/array/netcdfarray.py
  cf/data/array/raggedcontiguousarray.py
  cf/data/array/raggedindexedarray.py
  cf/data/array/raggedindexedcontiguousarray.py
  cf/data/array/subsampledarray.py
  cf/data/array/umarray.py
  cf/data/creation.py
  cf/data/data.py
  cf/data/fragment/__init__.py
  cf/data/fragment/abstract/__init__.py
  cf/data/fragment/abstract/fragmentarray.py
  cf/data/fragment/missingfragmentarray.py
  cf/data/fragment/netcdffragmentarray.py
  cf/data/fragment/umfragmentarray.py
  cf/data/gatheredarray.py
  cf/data/mixin/__init__.py
  cf/data/netcdfarray.py
  cf/data/subsampledarray.py
  cf/data/umarray.py
  cf/docstring/docstring.py
  cf/field.py
  cf/read_write/netcdf/netcdfread.py
  cf/read_write/um/umread.py
  cf/subspacefield.py
  cf/test/test_dsg.py
  cf/test/test_gathering.py
Labels: dask

#494 dask: Cached first, second and last data values
  cf/data/data.py
  cf/read_write/netcdf/netcdfread.py
  cf/test/test_Data.py
Labels: dask

#497 Move test to `ppTest`
  cf/test/test_pp.py
  cf/test/test_read_write.py
Labels: low priority

#496 Write omit data
  Changelog.rst
  cf/read_write/write.py
  cf/test/test_read_write.py
Labels: low priority

#489 dask: Remove deprecated tests from `test_general.py`
  cf/test/test_general.py
Labels: low priority, dask

#503 LAMA to Dask: trivial fixes for passing `test_{decorators, style}`
  cf/read_write/netcdf/netcdfread.py
  cf/test/test_decorators.py
Labels: testing, dask

#506 dask: Fix for cached str-type data elements
  cf/read_write/netcdf/netcdfread.py
Labels: dask

#505 dask: Merge duplicate PP tests
  cf/test/test_pp.py
Labels: low priority, dask
