Repository NCAS-CMS/cf-python, pull requests merged in 2022-12, with the labels that each got.

#498 dask: `Data.get_filenames` (3)
  cf/data/data.py
  cf/data/mixin/deprecations.py
  cf/domain.py
  cf/mixin/propertiesdata.py
  cf/test/test_Data.py
  docs/source/class/cf.Data.rst
Labels: dask

#502 dask: Subsampled compression
  cf/__init__.py
  cf/cfimplementation.py
  cf/interpolationparameter.py
  cf/test/test_subsampling.py
  cf/tiepointindex.py
Labels: low priority, dask

#504 dask: Deprecate `close`
  cf/abstract/constructlist.py
  cf/constructs.py
  cf/coordinatereference.py
  cf/domain.py
  cf/field.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/test/test_FieldList.py
  cf/test/test_geometry.py
Labels: low priority, dask

#515 dask: Remove CFA-0.4 base test
  cf/test/test_cfa.py
Labels: dask

#518 dask: Remove `FileArrayMixin._dask_lock`
  cf/data/array/mixin/filearraymixin.py
Labels: performance, dask

#519 dask: `Field.persist`
  cf/data/data.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/test/test_Data.py
  cf/test/test_DimensionCoordinate.py
  cf/test/test_Field.py
  docs/source/class/cf.AuxiliaryCoordinate.rst
  docs/source/class/cf.Bounds.rst
  docs/source/class/cf.CellMeasure.rst
  docs/source/class/cf.Count.rst
  docs/source/class/cf.Data.rst
  docs/source/class/cf.DimensionCoordinate.rst
  docs/source/class/cf.DomainAncillary.rst
  docs/source/class/cf.Field.rst
  docs/source/class/cf.FieldAncillary.rst
  docs/source/class/cf.Index.rst
  docs/source/class/cf.List.rst
Labels: low priority, dask

#507 Dask subarray graph structure - give subarrays/fragment arrays their own keys
  cf/data/array/cfanetcdfarray.py
  cf/data/array/gatheredarray.py
  cf/data/array/mixin/raggedarraymixin.py
  cf/data/array/subsampledarray.py
Labels: low priority, dask

#524 Set module in `unittest.main` for all test modules
  cf/test/create_test_files.py
  cf/test/setup_create_field.py
  cf/test/test_AuxiliaryCoordinate.py
  cf/test/test_CellMeasure.py
  cf/test/test_CellMethod.py
  cf/test/test_Constructs.py
  cf/test/test_CoordinateReference.py
  cf/test/test_Count.py
  cf/test/test_Data.py
  cf/test/test_Data_utils.py
  cf/test/test_Datetime.py
  cf/test/test_DimensionCoordinate.py
  cf/test/test_Domain.py
  cf/test/test_DomainAncillary.py
  cf/test/test_DomainAxis.py
  cf/test/test_Field.py
  cf/test/test_FieldAncillary.py
  cf/test/test_FieldList.py
  cf/test/test_Index.py
  cf/test/test_List.py
  cf/test/test_Maths.py
  cf/test/test_Query.py
  cf/test/test_RegridOperator.py
  cf/test/test_TimeDuration.py
  cf/test/test_aggregate.py
  cf/test/test_cfa.py
  cf/test/test_collapse.py
  cf/test/test_decorators.py
  cf/test/test_docstring.py
  cf/test/test_dsg.py
  cf/test/test_external.py
  cf/test/test_formula_terms.py
  cf/test/test_functions.py
  cf/test/test_gathering.py
  cf/test/test_general.py
  cf/test/test_geometry.py
  cf/test/test_groups.py
  cf/test/test_pp.py
  cf/test/test_read_write.py
  cf/test/test_regrid.py
  cf/test/test_style.py
  cf/test/test_subsampling.py
Labels: testing

#516 Improve `Field.collapse` error messages
  cf/field.py
Labels: low priority

#517 dask: Correctly read VLEN string variables
  cf/read_write/netcdf/netcdfread.py
  cf/test/test_groups.py
Labels: low priority, dask

#520 LAMA to Dask: updates to fix CI workflow setup errors
  .github/workflows/dask-migration-testing.yml
  .github/workflows/linting.yml
  .github/workflows/run-test-suite.yml
  .github/workflows/test-source-dist.yml
  setup.py
Labels: CI, dask

#510 dask: Fix for cached elements from size-0 arrays
  cf/read_write/netcdf/netcdfread.py
Labels: low priority, dask

#528 dask: Force from_array lock=False for nested arrays in compressed chunks
  cf/data/array/gatheredarray.py
  cf/data/array/mixin/__init__.py
  cf/data/array/mixin/compressedarraymixin.py
  cf/data/array/mixin/raggedarraymixin.py
  cf/data/array/subsampledarray.py
  cf/data/creation.py
  cf/data/data.py
  cf/test/test_Data.py
  cf/test/test_dsg.py
  cf/test/test_gathering.py
  cf/test/test_groups.py
  cf/test/test_subsampling.py
Labels: dask

#483 Fix edge case for cell methods when there are no coordinates
  cf/cfimplementation.py
  cf/mixin/fielddomain.py
  cf/test/test_Field.py
Labels: low priority, dask

#531 dask: Reinstate netCDF lock
  cf/data/array/netcdfarray.py
  cf/data/creation.py
  cf/data/data.py
  cf/test/test_read_write.py
Labels: high priority, dask

#523 Fix `DimensionCoordinate.create_bounds` for cyclic coordinates & improve docs
  Changelog.rst
  cf/dimensioncoordinate.py
  cf/test/test_DimensionCoordinate.py
Labels: low priority

#537 dask: Remove `Data.force_compute` and `Data.can_compute`
  cf/data/data.py
Labels: low priority, dask

#536 dask: Remove `is_small` and `is_very_small`
  cf/data/data.py
  cf/data/utils.py
Labels: low priority, dask

#538 LAMA to Dask: update `cf.environment` with new dependencies
  cf/functions.py
Labels: dask
