Repository NCAS-CMS/cf-python, pull requests merged in 2023-05, with the labels that each got.

#650 Fix bug when using the `-d` option to the `cfa` script
  Changelog.rst
  scripts/cfa
Labels: bug

#651 Added recipe to plot joint histogram
  docs/_downloads/plot_9_recipe.ipynb
  docs/_downloads/plot_9_recipe.py
  docs/_downloads/recipes_jupyter.zip
  docs/_downloads/recipes_python.zip
  docs/_images/sphx_glr_plot_9_recipe_001.png
  docs/_images/sphx_glr_plot_9_recipe_thumb.png
  docs/recipes/index.html
  docs/recipes/plot_9_recipe.html
  docs/source/recipes/filter.rst
  docs/source/recipes/plot_9_recipe.py
Labels: documentation

#648 `Data.argmin` and `Field.argmin` methods
  Changelog.rst
  cf/data/data.py
  cf/field.py
  cf/test/test_Data.py
  cf/test/test_Field.py
  docs/source/class/cf.Data.rst
  docs/source/class/cf.Field.rst
Labels: enhancement

#654 Fix the return type of `cf.example_fields`
  Changelog.rst
  cf/examplefield.py
  cf/test/test_functions.py
Labels: bug

#647 Speed up aggregation
  Changelog.rst
  cf/__init__.py
  cf/aggregate.py
  cf/cellmethod.py
  cf/constructlist.py
  cf/coordinatereference.py
  cf/data/data.py
  cf/data/utils.py
  cf/dimensioncoordinate.py
  cf/docstring/docstring.py
  cf/examplefield.py
  cf/field.py
  cf/fieldlist.py
  cf/flags.py
  cf/formula_terms.py
  cf/functions.py
  cf/mixin/fielddomain.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/query.py
  cf/read_write/netcdf/netcdfread.py
  cf/read_write/read.py
  cf/read_write/um/umread.py
  cf/test/test_Data.py
  cf/test/test_DimensionCoordinate.py
  cf/test/test_aggregate.py
  cf/test/test_functions.py
  cf/timeduration.py
  docs/source/class/cf.Data.rst
  docs/source/function.rst
  docs/source/installation.rst
  requirements.txt
Labels: bug, performance, aggregation
