Repository NCAS-CMS/cf-python, pull requests merged in 2023-01, with the labels that each got.

#526 dask: Bug fix to `convert_to_reftime`
  cf/data/utils.py
  cf/test/test_Data_utils.py
Labels: low priority, dask

#549 dask: Linting
  cf/data/array/netcdfarray.py
  cf/data/data.py
  cf/test/test_Field.py
Labels: dask

#547 dask: Fix `GatheredArray` syntax in tutorial
  docs/source/tutorial.rst
Labels: documentation, low priority, dask

#550 dask: Remove CachedArray class
  cf/__init__.py
  cf/data/array/__init__.py
  cf/data/array/cachedarray.py
Labels: dask

#560 Back port of `cf.DimensionCoordinate.create_bounds` docs to 3.13.1
  cf/dimensioncoordinate.py
  docs/method/cf.DimensionCoordinate.create_bounds.html
Labels: documentation

#562 README updates
  README.md
Labels: documentation

#551 dask: `Data.__init__` with no arguments
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#559 Added recipes for the first time
  docs/source/images/annual_mean_temp.png
  docs/source/images/anomaly.png
  docs/source/images/global_mean_map.png
  docs/source/images/global_mean_temp.png
  docs/source/images/june1995_preci.png
  docs/source/index.rst
  docs/source/recipes.rst
Labels: documentation

#566 Recipes to master
  docs/source/images/annual_mean_temp.png
  docs/source/images/anomaly.png
  docs/source/images/global_mean_map.png
  docs/source/images/global_mean_temp.png
  docs/source/images/june1995_preci.png
  docs/source/index.rst
  docs/source/recipes.rst
Labels: documentation

#567 Housekeeping
  Changelog.rst
  README.md
  cf/__init__.py
  cf/abstract/constructlist.py
  cf/aggregate.py
  cf/cfdatetime.py
  cf/constructlist.py
  cf/data/array/abstract/array.py
  cf/data/array/cfanetcdfarray.py
  cf/data/array/fullarray.py
  cf/data/array/gatheredarray.py
  cf/data/array/mixin/raggedarraymixin.py
  cf/data/array/subsampledarray.py
  cf/data/array/umarray.py
  cf/data/data.py
  cf/data/mixin/deprecations.py
  cf/docstring/docstring.py
  cf/domain.py
  cf/field.py
  cf/fieldlist.py
  cf/flags.py
  cf/functions.py
  cf/mixin/coordinate.py
  cf/mixin/fielddomain.py
  cf/mixin/properties.py
  cf/mixin/propertiesdata.py
  cf/query.py
  cf/read_write/netcdf/netcdfread.py
  cf/read_write/read.py
  cf/read_write/um/umread.py
  cf/timeduration.py
  docs/source/installation.rst
  docs/source/introduction.rst
  docs/source/releases.rst
  docs/source/spelling_false_positives.txt
  docs/source/tutorial.rst
  release_docs
  requirements.txt
Labels: documentation

#570 dask: work-around for __setitem__ of masked element on str array
  cf/test/individual_tests
  cf/test/setup_create_field.py
Labels: dask

#545 dask: More performance docs
  cf/data/data.py
Labels: documentation, low priority, dask

#539 dask: Deal with TODODASKMSG placeholders
  cf/data/mixin/deprecations.py
Labels: low priority, dask

#569 Fixed typo
  cf/auxiliarycoordinate.py
Labels: documentation

#540 dask: Deal with TODODASKDOCS placeholders
  Changelog.rst
  cf/data/array/cfanetcdfarray.py
  cf/data/array/fullarray.py
  cf/data/array/gatheredarray.py
  cf/data/array/mixin/arraymixin.py
  cf/data/array/mixin/raggedarraymixin.py
  cf/data/array/subsampledarray.py
  cf/data/array/umarray.py
  cf/data/data.py
  cf/data/fragment/missingfragmentarray.py
  cf/field.py
  cf/mixin/propertiesdata.py
Labels: low priority, dask

#548 dask: `Data.datetime_array` bug fix
  cf/data/data.py
  cf/test/test_Data.py
Labels: high priority, dask

#522 dask: `cf.read` chunks
  Changelog.rst
  cf/read_write/netcdf/netcdfread.py
  cf/read_write/read.py
  cf/test/test_read_write.py
Labels: high priority, dask

#532 dask: `Data.cull_graph`, concatenate and `Field.collapse`
  cf/aggregate.py
  cf/data/data.py
  cf/docstring/docstring.py
  cf/field.py
  cf/fieldlist.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/test/test_Data.py
  cf/test/test_Field.py
  cf/test/test_FieldList.py
  cf/test/test_collapse.py
  docs/source/class/cf.Data.rst
Labels: high priority, dask

#479 `cf.read` and `cf.Constructs` docs updates
  cf/constructs.py
  cf/read_write/read.py
Labels: documentation, low priority, dask

#564 dask: Allow weighted sums in `Data.stats`
  cf/data/data.py
  cf/test/test_Data.py
Labels: low priority, dask

#575 dask: Indices equality test order
  cf/mixin/fielddomain.py
  cf/test/test_Field.py
Labels: dask

#572 LAMA to Dask: misc. fixes for a passing `test_aggregate`
  cf/aggregate.py
  cf/data/data.py
  cf/test/test_aggregate.py
Labels: high priority, dask

#552 dask: `Container` inheritance
  cf/data/array/abstract/array.py
  cf/data/array/cfanetcdfarray.py
  cf/data/array/gatheredarray.py
  cf/data/array/netcdfarray.py
  cf/data/array/raggedcontiguousarray.py
  cf/data/array/raggedindexedarray.py
  cf/data/array/raggedindexedcontiguousarray.py
  cf/data/array/subsampledarray.py
Labels: high priority, dask

#554 dask: `cf.size`
  cf/cfdatetime.py
  cf/field.py
  cf/functions.py
  cf/mixin/propertiesdatabounds.py
  cf/test/test_functions.py
Labels: high priority, dask

#557 dask: `Field.argmax`
  cf/data/data.py
  cf/field.py
  cf/test/test_Data.py
  cf/test/test_Field.py
  docs/source/class/cf.Field.rst
Labels: high priority, dask

#578 dask: Update docstring substitutions
  cf/data/array/cfanetcdfarray.py
  cf/data/array/fullarray.py
  cf/data/array/umarray.py
  cf/data/data.py
  cf/data/fragment/missingfragmentarray.py
  cf/data/fragment/netcdffragmentarray.py
  cf/data/fragment/umfragmentarray.py
  cf/field.py
Labels: documentation, dask

#553 dask: `convert_reference_time` methods
  cf/data/dask_utils.py
  cf/data/data.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/test/test_Data.py
  docs/source/class/cf.Data.rst
Labels: high priority, dask

#541 dask: Deal with some (but not all) TODODASK placeolders
  cf/data/dask_utils.py
  cf/data/data.py
  cf/data/fragment/abstract/fragmentarray.py
  cf/data/utils.py
  cf/domain.py
  cf/field.py
  cf/functions.py
  cf/mixin/fielddomain.py
  cf/test/test_Data_utils.py
Labels: documentation, low priority, dask

#438 dask: `cf.Field.regrids` and `cf.Field.regridc`
  MANIFEST.in
  cf/data/dask_regrid.py
  cf/data/data.py
  cf/docstring/docstring.py
  cf/domain.py
  cf/field.py
  cf/maths.py
  cf/read_write/um/umread.py
  cf/regrid/__init__.py
  cf/regrid/regrid.py
  cf/regrid/regridoperator.py
  cf/regrid/utils.py
  cf/test/create_test_files.py
  cf/test/regrid_file1.nc
  cf/test/regrid_file2.nc
  cf/test/regrid_file3.nc
  cf/test/regrid_file4.nc
  cf/test/regrid_file5.nc
  cf/test/regrid_file6.nc
  cf/test/regrid_file7.nc
  cf/test/regrid_file8.nc
  cf/test/test_RegridOperator.py
  cf/test/test_regrid.py
  docs/source/class/cf.RegridOperator.rst
Labels: dask, top priority

#543 dask: `Field.rechunk`
  cf/data/data.py
  cf/data/mixin/deprecations.py
  cf/docstring/docstring.py
  cf/functions.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/test/test_DimensionCoordinate.py
  docs/source/class/cf.AuxiliaryCoordinate.rst
  docs/source/class/cf.Bounds.rst
  docs/source/class/cf.CellMeasure.rst
  docs/source/class/cf.Count.rst
  docs/source/class/cf.Data.rst
  docs/source/class/cf.DimensionCoordinate.rst
  docs/source/class/cf.DomainAncillary.rst
  docs/source/class/cf.Field.rst
  docs/source/class/cf.FieldAncillary.rst
  docs/source/class/cf.Index.rst
  docs/source/class/cf.List.rst
Labels: low priority, dask

#563 dask: Catch `NotImplemented` resulting from arithmetic
  cf/data/data.py
  cf/test/test_Data.py
  cf/test/test_Field.py
Labels: low priority, dask

#581 dask: Housekeeping
  cf/data/data.py
  cf/data/mixin/deprecations.py
  cf/field.py
  cf/regrid/regrid.py
  cf/regrid/regridoperator.py
Labels: dask

#582 dask: Miscellaneous test fixes
  cf/maths.py
  cf/test/test_Data_utils.py
  cf/test/test_Field.py
Labels: dask

#542 dask: Performance docs
  cf/data/data.py
  cf/functions.py
  docs/source/Changelog.rst
  docs/source/aggregation_rules.rst
  docs/source/api_reference.rst
  docs/source/cf_data_model.rst
  docs/source/class/cf.Data.rst
  docs/source/conf.py
  docs/source/images/dask_task_graph.svg
  docs/source/installation.rst
  docs/source/introduction.rst
  docs/source/performance.rst
  docs/source/releases.rst
  docs/source/tutorial.rst
  release_docs
Labels: documentation, low priority, dask
