Repository NCAS-CMS/cf-python, pull requests merged in 2023-03, with the labels that each got.

#606 Allow `cf.aggregate` to retain external cell measures
  Changelog.rst
  cf/aggregate.py
  cf/test/test_external.py
Labels: aggregation

#603 Allow `relaxed_units` in `cf.aggregate` to cope with invalid (in addition to missing) units
  Changelog.rst
  cf/aggregate.py
  cf/data/data.py
  cf/test/test_Data.py
  cf/test/test_aggregate.py
Labels: aggregation

#607 Refactor the modification of components when setting a new Dask array with `Data._set_dask`
  cf/data/data.py
  cf/test/test_Data.py
Labels: dask

#613 Drop Python 3.7 support (via `numpy>=1.22` req.) loose ends
  .github/workflows/run-test-suite.yml
  .github/workflows/test-source-dist.yml
Labels: installation, GitHub Actions, release
