Repository NCAS-CMS/cf-python, pull requests merged in 2023-06, with the labels that each got.

#656 Added Cheat Sheet
  docs/source/cheat_sheet.rst
  docs/source/index.rst
Labels: documentation

#659 Scrollable Navigation Menu (Sidebar)
  docs/source/_static/customise-alabaster.css
  docs/source/conf.py
Labels: documentation

#660 Automate Recipe filtering
  DOCUMENTATION.md
  docs/source/recipes/README.rst
  docs/source/recipes/filter.rst
  docs/source/recipes/recipe_list.txt
  release_docs
Labels: documentation

#634 Added method to create a new domain object for the specified bounds and axes
  cf/dimensioncoordinate.py
  cf/domain.py
  cf/test/test_DimensionCoordinate.py
  cf/test/test_Domain.py
  docs/source/class/cf.DimensionCoordinate.rst
  docs/source/class/cf.Domain.rst
  docs/source/field_analysis.rst
  docs/source/recipes/plot_6_recipe.py
Labels: enhancement, regridding

#662 Added PDF for Cheat Sheet
  README.md
  RELEASE.md
  docs/_downloads/cheatsheet.pdf
  docs/source/cheat_sheet.rst
  release_docs
Labels: documentation

#666 Regrid chunks
  cf/data/data.py
  cf/test/test_regrid.py
  docs/source/conf.py
  docs/source/recipes/plot_11_recipe.py
Labels: bug, regridding

#668 Fix bug in `cf.read` for some PP data with a single vertical level
  Changelog.rst
  cf/read_write/um/umread.py
Labels: bug, um/pp

#670 Docs: remove or replace cases of some subjective filler terms
  docs/source/field_analysis.rst
  docs/source/installation.rst
  docs/source/introduction.rst
  docs/source/performance.rst
  docs/source/tutorial.rst
Labels: documentation

#671 In `cf.read`, skip caching elements from compression index variables.
  cf/__init__.py
  cf/read_write/netcdf/netcdfread.py
  docs/source/installation.rst
  requirements.txt
Labels: performance

#674 `cf.aggregate` "cells" keyword
  Changelog.rst
  cf/__init__.py
  cf/aggregate.py
  cf/data/data.py
  cf/functions.py
  cf/mixin/propertiesdata.py
  cf/mixin/propertiesdatabounds.py
  cf/query.py
  cf/test/test_Query.py
  cf/test/test_TimeDuration.py
  cf/test/test_aggregate.py
  cf/timeduration.py
  docs/source/class/cf.AuxiliaryCoordinate.rst
  docs/source/class/cf.Bounds.rst
  docs/source/class/cf.CellMeasure.rst
  docs/source/class/cf.Count.rst
  docs/source/class/cf.Data.rst
  docs/source/class/cf.DimensionCoordinate.rst
  docs/source/class/cf.DomainAncillary.rst
  docs/source/class/cf.Field.rst
  docs/source/class/cf.FieldAncillary.rst
  docs/source/class/cf.Index.rst
  docs/source/class/cf.List.rst
  docs/source/class/cf.Query.rst
  docs/source/class/cf.TimeDuration.rst
  docs/source/function.rst
  docs/source/tutorial.rst
Labels: enhancement, aggregation
