Repository NCAS-CMS/cf-python, pull requests merged in 2024-04, with the labels that each got.

#755 Fix bug in `cf.aggregate` that sometimes put a null transpose operation into the Dask grpah when one was not needed
  Changelog.rst
  cf/aggregate.py
Labels: bug, performance, active storage

#753 Open and half-open intervals for `wi` queries
  Changelog.rst
  cf/query.py
  cf/test/test_Query.py
Labels: enhancement

#760 Allow a halo to be added by `indices` and `subspace`
  Changelog.rst
  cf/docstring/docstring.py
  cf/domain.py
  cf/field.py
  cf/functions.py
  cf/mixin/fielddomain.py
  cf/subspacefield.py
  cf/test/test_Field.py
  cf/test/test_functions.py
  docs/attribute/cf.Domain.indices.html
  docs/attribute/cf.Domain.subspace.html
  docs/attribute/cf.Field.indices.html
  docs/method/cf.Field.subspace.html
  docs/source/class/cf.Domain.rst
  docs/source/class/cf.Field.rst
Labels: enhancement

#765 Fix `cf.aggregate` for actual_range and np.array properties
  Changelog.rst
  cf/aggregate.py
  cf/test/test_aggregate.py
  docs/source/contributing.rst
Labels: bug, aggregation
