Repository NCAS-CMS/cf-python, pull requests merged in 2024-11, with the labels that each got.

#829 Code tidy
  Changelog.rst
  cf/test/test_Data.py
  cf/test/test_Field.py
  cf/test/test_FullArray.py
  cf/test/test_NetCDF4Array.py
  cf/test/test_active_storage.py
  cf/test/test_functions.py
  cf/test/test_read_write.py
Labels: code tidy

#818 Add new recipe (16) by summer student: projection subplots
  docs/source/recipes/plot_16_recipe.py
  docs/source/recipes/recipe_list.txt
Labels: documentation

#820 Add new recipe (18) by summer student: correlation calculation
  docs/source/recipes/plot_18_recipe.py
  docs/source/recipes/recipe_list.txt
Labels: documentation

#821 Add new recipe (19) as started by summer student: per-season trends
  docs/source/recipes/plot_19_recipe.py
  docs/source/recipes/recipe_list.txt
Labels: documentation

#822 Add new recipe (20) started by summer student: current divergence
  docs/source/recipes/plot_20_recipe.py
  docs/source/recipes/recipe_list.txt
Labels: documentation

#830 Fix bug where `cf.Field.subspace` doesn't always correctly handle global cyclic subspaces
  Changelog.rst
  cf/cfimplementation.py
  cf/data/data.py
  cf/dimensioncoordinate.py
  cf/mixin/fielddomain.py
  cf/regrid/regrid.py
  cf/test/test_DimensionCoordinate.py
  cf/test/test_Field.py
Labels: bug
