Repository NCAS-CMS/cf-python, pull requests merged in 2025-04, with the labels that each got.

#860 Fix bug that caused wrong directions from `cf.DimensionCoordinate.direction`
  Changelog.rst
  cf/dimensioncoordinate.py
  cf/test/test_DimensionCoordinate.py
Labels: bug

#861 Recipes tweaks for Sphinx Gallery build and rendering
  docs/source/recipes/plot_04_recipe.py
  docs/source/recipes/plot_16_recipe.py
  docs/source/recipes/plot_17_recipe.py
  docs/source/recipes/plot_18_recipe.py
  docs/source/recipes/plot_19_recipe.py
  docs/source/recipes/plot_20_recipe.py
  release_docs
Labels: documentation, release

#862 Add "isort:skip_file" directives to recipes
  cf/test/test_DimensionCoordinate.py
  docs/source/conf.py
  docs/source/recipes/plot_08_recipe.py
  docs/source/recipes/plot_12_recipe.py
  docs/source/recipes/plot_13_recipe.py
  docs/source/recipes/plot_17_recipe.py
  docs/source/recipes/plot_18_recipe.py
  docs/source/recipes/plot_19_recipe.py
Labels: linting
